FROM bict/human-detect-module-base

WORKDIR /app

# Poetry 설정 및 의존성 설치
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

# 코드 마운트를 전제로 실행
CMD ["bash"]
